twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme: ['bootstrap_5_layout.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # On déclare ci-dessous le nom de la variable globale
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        locales: '%app.locales%'

when@test:
    twig:
        strict_variables: true
